
all:sort.o Binary_search.o
	gcc -O1 -g -o sort.o Binary_search.o

sort.o:sort.c sort.h
	gcc -O1 -g -c sort.c

Binary_search.o:binary_search/Binary_search.c binary_search/Binary_search.h
	gcc -O1 -g -c binary_search/Binary_search.c


